# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Riley's Eyes 
tagline:          'My creative outlet'
description:      'A repository for the machinations of my mind'
url:              https://rileyseyes.github.io
baseurl:          /

author:
  name:           'Riley'
  url:            https://rileyseyes.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
